### ISSUE TITLE
there are two “left_ankle”

### ISSUE THREAD

**Issue by gemlongman** [eherr/motion_preprocessing_tool#1]
https://github.com/eherr/motion_preprocessing_tool/blob/772e793d129c0a160546755fc328611f9ab61b99/motion_analysis/gui/dialogs/skeleton_editor_dialog.py#L72
Seemingly it doesn't matter~

**Comment by eherr** [comment]
Thanks for reporting that. I fixed it in a new commit. Yes this list only affected the labels for a combobox in the GUI.
