### ISSUE TITLE
ModuleNotFoundError: No module named 'vis_utils'

### ISSUE THREAD

**Issue by zhou-fy** [eherr/motion_preprocessing_tool#10]
Hello, I got the following error when installing vis_utils. I use windows. Is there any way to solve this problem?
<img width="866" alt="error" src="https://github.com/eherr/motion_preprocessing_tool/assets/86836938/98e5d801-396e-48b5-bada-e3afc14b9168">

**Comment by eherr** [comment]
Sorry for the late response. I should remove the noise library from the dependencies of vis_utils. If you check it out you can manually remove it. When it is missing it should ignore it during the imports.

**Comment by zhou-fy** [comment]
> Sorry for the late response. I should remove the noise library from the dependencies of vis_utils. If you check it out you can manually remove it. When it is missing it should ignore it during the imports.

I see! After I deleted this item, I successfully installed and ran it, thank you!
