### ISSUE TITLE
"Guess Coordinate Systems" set all joints, so what does this mean?

### ISSUE THREAD

**Issue by gemlongman** [eherr/motion_preprocessing_tool#2]
https://github.com/eherr/motion_preprocessing_tool/blob/a974da3329825b8bd35757d0a2c517bd91ced0d0/motion_analysis/gui/dialogs/skeleton_editor_dialog.py#L628

Excuse me, actually,  it supposed that clicking "Guess Coordinate Systems" or "Reset Coordinate Systems" bottom will update all joints "cos" without selecting any joints. 
However, they need to select a joint in advance, "Guess Coordinate Systems" sets all joints, while "Reset Coordinate Systems" only sets the selected joint. 

Are there some issues here?

**Comment by eherr** [comment]
You are right this is confusing. I will change the buttons to guess/reset the coordinate system of the current joint and will add extra buttons at the bottom of the dialog that will guess/reset the coordinate systems for all joints.

**Comment by eherr** [comment]
I have uploaded now a new version with buttons affecting all joints or only the selected joint.

**Comment by gemlongman** [comment]
wow, it is so efficient!
