### ISSUE TITLE
scikit_learn update

### ISSUE THREAD

**Issue by Max-ChenFei** [eherr/motion_preprocessing_tool#4]
In the _requirements.txt, scikit_learn>=0.23.2, but 
> FutureWarning: The sklearn.mixture.gaussian_mixture module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.mixture. Anything that cannot be imported from sklearn.mixture is now part of the private API.

either set scikit_learn==0.23.2 or update the import at line 31 inmotion_preprocessing_tool\tool\plugins\morphablegraphs\core\motion_generator\optimization\objective_functions.py

**Comment by eherr** [comment]
Thanks I have fixed the version for now.
