### ISSUE TITLE
ModuleNotFoundError: No module named 'morphablegraphs'

### ISSUE THREAD

**Issue by Max-ChenFei** [eherr/motion_preprocessing_tool#5]
When I run main.py, 

> from morphablegraphs.constraints.constraint_builder import ConstraintBuilder, MockActionConstraints 

at line 32 in mg_state_planner.py inside morphablegraphs.

bug: ModuleNotFoundError: No module named 'morphablegraphs' 

The morhpablegraphs is not imported.

**Comment by Max-ChenFei** [comment]
Even this morhpablegraphs  module is imported, it should be morphablegraphs.core.constraints if not import constraints in __init__ of morphablegraphs module.

**Comment by eherr** [comment]
Thanks for testing it. It somehow worked for me. I will change this submodule into a python package so that you can install it using pip.

**Comment by eherr** [comment]
I have changed morphablegraphs now to be installable as a package using PIP. Due to an optional submodule it has to be checked out manually.

**Comment by Max-ChenFei** [comment]
Thanks, it works now. 👍
