### ISSUE TITLE
Warning, no uniform: lights

### ISSUE THREAD

**Issue by WYM-1999** [eherr/motion_preprocessing_tool#9]
Hello, after I cloned the project and configured the environment to run according to readme, I got two warning prompts: **Warning, no uniform: lights**, **QOpenGLContext:: swapBuffer() called with non-exposed window, behavior is undefined**, and I got a white interface. Do you know what went wrong?
![image](https://user-images.githubusercontent.com/34278160/218655968-7d862768-f823-42cb-8989-64296c065fa2.png)
![image](https://user-images.githubusercontent.com/34278160/218656036-aaca5547-e88f-462e-b568-0f8b1ef40006.png)

**Comment by eherr** [comment]
Hi, sorry the warnings are misleading. It looks like a recent change I made to the vis_utils is the reason for the ground not being created. I will look into it.

**Comment by eherr** [comment]
Sorry for taking so long to respond. I tested it again with the latest versions and it loads correctly.
![image](https://user-images.githubusercontent.com/14311090/223517985-6a5c9c19-e75c-4707-94b8-c13864f26ad3.png)

**Comment by WYM-1999** [comment]
Thank you for your letter.
Sorry, I just checked my mailbox.I tried again and got the correct operation.
It's a great project.Thank you for your work. I hope everything goes well.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eherr/motion_preprocessing_tool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月8日(星期三) 凌晨2:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eherr/motion_preprocessing_tool] Warning, no uniform: lights (Issue #9)





 
Sorry for taking so long to respond. I tested it again with the latest versions and it seem to load correctly.

**Comment by eherr** [comment]
Thanks for testing and thank you for your kind words.
